package app

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"strings"
	"sync"
	"time"

	"github.com/google/generative-ai-go/genai"
	"github.com/google/uuid"
	"golang.org/x/oauth2"
	"golang.org/x/oauth2/google"
	oauth2v2 "google.golang.org/api/oauth2/v2"
	"google.golang.org/api/option"
)

// AnalysisService
type AnalysisService struct {
	client *genai.Client
	model  *genai.GenerativeModel
	cache  sync.Map
}

func NewAnalysisService(ctx context.Context, apiKey string) (*AnalysisService, error) {
	if apiKey == "" {
		apiKey = strings.TrimSpace(os.Getenv("GEMINI_API_KEY"))
	}
	if apiKey == "" {
		return nil, fmt.Errorf("GEMINI_API_KEY not set")
	}

	client, err := genai.NewClient(ctx, option.WithAPIKey(apiKey))
	if err != nil {
		return nil, err
	}

	return &AnalysisService{
		client: client,
		model:  client.GenerativeModel("gemini-flash-latest"),
	}, nil
}

func (s *AnalysisService) Close() error {
	return s.client.Close()
}

func (s *AnalysisService) Analyze(ctx context.Context, cveData *CVEData, webResults string, userToken string) (string, error) {
	id := "N/A"
	if cveData != nil && cveData.ID != "" {
		id = cveData.ID
		if val, ok := s.cache.Load(id); ok {
			return val.(string), nil
		}
	}

	desc, severity, score := "Detailed description from primary databases is currently unavailable.", "UNKNOWN", 0.0
	if cveData != nil {
		if cveData.Description != "" { desc = cveData.Description }
		if cveData.Severity != "" { severity = cveData.Severity }
		if cveData.Score > 0 { score = cveData.Score }
	}

	prompt := fmt.Sprintf(promptTemplate, id, desc, severity, score, webResults)
	
	var model *genai.GenerativeModel
	if userToken != "" {
		// Use user's OAuth token
		src := oauth2.StaticTokenSource(&oauth2.Token{AccessToken: userToken})
		client, err := genai.NewClient(ctx, option.WithTokenSource(src))
		if err != nil {
			return "", fmt.Errorf("user token error: %w", err)
		}
		defer client.Close()
		model = client.GenerativeModel("gemini-flash-latest")
	} else {
		// Use global model
		model = s.model
	}

	resp, err := model.GenerateContent(ctx, genai.Text(prompt))
	if err != nil {
		return "", fmt.Errorf("gemini error: %w", err)
	}

	if len(resp.Candidates) == 0 || resp.Candidates[0].Content == nil {
		return "", fmt.Errorf("no content generated by AI")
	}

	var summary strings.Builder
	for _, part := range resp.Candidates[0].Content.Parts {
		if txt, ok := part.(genai.Text); ok {
			summary.WriteString(string(txt))
		}
	}
	
	result := summary.String()
	if result == "" {
		return "", fmt.Errorf("AI generated empty response")
	}
	
	if id != "N/A" {
		s.cache.Store(id, result)
	}
	
	return result, nil
}

// Server
type Server struct {
	logger      *slog.Logger
	analyzer    *AnalysisService
	github      *GitHub
	nvd         *NVD
	osv         *OSV
	oauthConfig *oauth2.Config
	authEnabled bool
}

func NewServer(logger *slog.Logger, analyzer *AnalysisService, github *GitHub, nvd *NVD, osv *OSV) *Server {
	clientID := os.Getenv("GOOGLE_CLIENT_ID")
	clientSecret := os.Getenv("GOOGLE_CLIENT_SECRET")
	redirectURL := os.Getenv("REDIRECT_URL")
	
	authEnabled := clientID != "" && clientSecret != ""

	var conf *oauth2.Config
	if authEnabled {
		conf = &oauth2.Config{
			ClientID:     clientID,
			ClientSecret: clientSecret,
			RedirectURL:  redirectURL,
			Scopes: []string{
				"https://www.googleapis.com/auth/userinfo.email",
				"https://www.googleapis.com/auth/generative-language",
			},
			Endpoint: google.Endpoint,
		}
	}

	return &Server{
		logger:      logger,
		analyzer:    analyzer,
		github:      github,
		nvd:         nvd,
		osv:         osv,
		oauthConfig: conf,
		authEnabled: authEnabled,
	}
}


func (s *Server) Routes() http.Handler {
	mux := http.NewServeMux()
	
	// Static files with aggressive caching
	fileServer := http.FileServer(http.Dir("./ui/static/"))
	mux.Handle("/static/", http.StripPrefix("/static/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Cache-Control", "public, max-age=31536000, immutable")
		fileServer.ServeHTTP(w, r)
	})))

	mux.HandleFunc("/", s.handleHome)
	mux.HandleFunc("/api/cve", s.handleCVE)
	mux.HandleFunc("/api/config", s.handleConfig)
	mux.HandleFunc("/api/health", s.handleHealth)
	mux.HandleFunc("/login", s.handleLogin)
	mux.HandleFunc("/callback", s.handleCallback)
	mux.HandleFunc("/logout", s.handleLogout)
	return s.withMiddleware(mux)
}

func (s *Server) handleHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusOK)
	w.Write([]byte("ok"))
}

func (s *Server) handleConfig(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	
	userEmail := ""
	hasUserToken := false
	if cookie, err := r.Cookie("session"); err == nil {
		userEmail = cookie.Value
	}
	if cookie, err := r.Cookie("user_token"); err == nil && cookie.Value != "" {
		hasUserToken = true
	}

	json.NewEncoder(w).Encode(map[string]interface{}{
		"authEnabled":  s.authEnabled,
		"userEmail":    userEmail,
		"hasUserToken": hasUserToken,
	})
}



func (s *Server) handleLogin(w http.ResponseWriter, r *http.Request) {
	if !s.authEnabled {
		http.Redirect(w, r, "/", http.StatusSeeOther)
		return
	}
	
	url := s.oauthConfig.AuthCodeURL("state", oauth2.AccessTypeOffline, oauth2.ApprovalForce)
	http.Redirect(w, r, url, http.StatusTemporaryRedirect)
}

func (s *Server) handleCallback(w http.ResponseWriter, r *http.Request) {
	if !s.authEnabled {
		http.Redirect(w, r, "/", http.StatusSeeOther)
		return
	}

	code := r.URL.Query().Get("code")
	token, err := s.oauthConfig.Exchange(r.Context(), code)
	if err != nil {
		s.logger.Error("token exchange failed", "error", err)
		http.Error(w, "Failed to exchange token", http.StatusInternalServerError)
		return
	}

	svc, err := oauth2v2.NewService(r.Context(), option.WithTokenSource(s.oauthConfig.TokenSource(r.Context(), token)))
	if err != nil {
		http.Error(w, "Failed to create oauth service", http.StatusInternalServerError)
		return
	}

	info, err := svc.Userinfo.V2.Me.Get().Do()
	if err != nil {
		http.Error(w, "Failed to get user info", http.StatusInternalServerError)
		return
	}

	// Store email in session cookie
	http.SetCookie(w, &http.Cookie{
		Name:     "session",
		Value:    info.Email,
		Path:     "/",
		HttpOnly: true,
		Secure:   false, 
		MaxAge:   86400,
	})

	// Store Access Token in a separate cookie
	http.SetCookie(w, &http.Cookie{
		Name:     "user_token",
		Value:    token.AccessToken,
		Path:     "/",
		HttpOnly: true,
		Secure:   false,
		MaxAge:   int(time.Until(token.Expiry).Seconds()),
	})

	http.Redirect(w, r, "/", http.StatusSeeOther)
}

func (s *Server) handleLogout(w http.ResponseWriter, r *http.Request) {
	if !s.authEnabled {
		http.Redirect(w, r, "/", http.StatusSeeOther)
		return
	}
	http.SetCookie(w, &http.Cookie{Name: "session", Value: "", Path: "/", MaxAge: -1})
	http.SetCookie(w, &http.Cookie{Name: "user_token", Value: "", Path: "/", MaxAge: -1})
	http.Redirect(w, r, "/", http.StatusSeeOther)
}

func (s *Server) handleHome(w http.ResponseWriter, r *http.Request) {
	if r.URL.Path != "/" {
		http.NotFound(w, r)
		return
	}
	http.ServeFile(w, r, "./ui/html/index.html")
}

func (s *Server) handleCVE(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	var req CVERequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, "Invalid request", http.StatusBadRequest)
		return
	}

	cveID, err := ValidateCVEID(req.CVE)
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	ctx := r.Context()
	var cveData *CVEData
	sourceName := ""

	// Try NVD then OSV
	if data, err := s.nvd.Fetch(ctx, cveID); err == nil {
		cveData, sourceName = data, "NVD"
	} else if data, err := s.osv.Fetch(ctx, cveID); err == nil {
		cveData, sourceName = data, "OSV"
	}

	searchResult, _ := s.github.Search(ctx, cveID)
	webContent := "No additional context found."
	if searchResult != nil {
		webContent = searchResult.Content
	}

	if cveData == nil && (searchResult == nil || !searchResult.SourceStatus["GitHub"]) {
		http.Error(w, "CVE not found in known databases or resources", http.StatusNotFound)
		return
	}

	userToken := ""
	if cookie, err := r.Cookie("user_token"); err == nil {
		userToken = cookie.Value
	}

	summary, err := s.analyzer.Analyze(ctx, cveData, webContent, userToken)
	if err != nil {
		s.logger.Error("analysis failed", "error", err)
		summary = fmt.Sprintf("Analysis currently unavailable: %v", err)
	}

	if sourceName == "" && searchResult != nil && searchResult.SourceStatus["GitHub"] {
		sourceName = "GitHub Advisories"
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]interface{}{
		"source":   sourceName,
		"summary":  summary,
		"severity": s.getSeverity(cveData),
		"score":    s.getScore(cveData),
	})
}

func (s *Server) getSeverity(d *CVEData) string {
	if d == nil { return "UNKNOWN" }
	return d.Severity
}

func (s *Server) getScore(d *CVEData) float64 {
	if d == nil { return 0.0 }
	return d.Score
}

// Middleware
func (s *Server) withMiddleware(h http.Handler) http.Handler {
	return s.recovery(s.requestID(s.securityHeaders(s.requireAuth(h))))
}

func (s *Server) requireAuth(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if !s.authEnabled {
			next.ServeHTTP(w, r)
			return
		}

		// Allow static files and auth endpoints
		if strings.HasPrefix(r.URL.Path, "/static/") || 
		   r.URL.Path == "/login" || 
		   r.URL.Path == "/callback" ||
		   r.URL.Path == "/api/config" ||
		   r.URL.Path == "/api/health" {
			next.ServeHTTP(w, r)
			return
		}

		cookie, err := r.Cookie("session")
		if err != nil || cookie.Value == "" {
			// If it's an API call, return 401
			if strings.HasPrefix(r.URL.Path, "/api/") {
				http.Error(w, "Unauthorized", http.StatusUnauthorized)
				return
			}
			// Otherwise redirect to login
			http.Redirect(w, r, "/login", http.StatusTemporaryRedirect)
			return
		}
		next.ServeHTTP(w, r)
	})
}

func (s *Server) securityHeaders(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("X-Content-Type-Options", "nosniff")
		w.Header().Set("X-Frame-Options", "DENY")
		w.Header().Set("X-XSS-Protection", "1; mode=block")
		next.ServeHTTP(w, r)
	})
}

func (s *Server) requestID(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		id := uuid.New().String()
		w.Header().Set("X-Request-ID", id)
		next.ServeHTTP(w, r)
	})
}

func (s *Server) recovery(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		defer func() {
			if err := recover(); err != nil {
				s.logger.Error("panic recovered", "error", err)
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
			}
		}()
		next.ServeHTTP(w, r)
	})
}

const promptTemplate = `
You are a security analyst. Create a clear summary using ALL available information.
ID: %s, Description: %s, Severity: %s, Score: %.1f
Context: %s
Format: ### Overview (3 paragraphs: What, How, Impact) and ### Sources (links).
`
